### ISSUE TITLE
Dimension errors in feedforward network serialization

### ISSUE THREAD

**Issue by tfburns** [DrChainsaw/ONNXmutable.jl#29]
I created a simple MNIST model using code shown in #26 and turned it into an ONNX model. I then tried to use this with the ONNX Runtime C++ MNIST sample shown [here](https://github.com/microsoft/onnxruntime/tree/master/samples/c_cxx/MNIST).

The ONNX model serialised by `ONNXmutable.jl` doesn't load after I adjusted the C++ code sample to account for dimensionality differences in the input. When I ran the model I got the following error: `Load model from model.onnx failed:Node (dense_0) Op (Gemm) [ShapeInferenceError] First input does not have rank 2`.

Viewing the resulting ONNX model using [Netron](https://github.com/lutzroeder/netron) I noticed several dimensionality errors internal to the model file relating to the output and input dimensions.
![image](https://user-images.githubusercontent.com/12498054/97989725-488f3c00-1e22-11eb-8173-ceb66cf6a4ca.png)

The input dimension is `[784]` when it should be `[1,784]`. This is because `Gemm` (General Matrix multiplication) expects to compute `Y = alpha * A' * B' + beta * C`, where `A` and `B` are tensors of `(M, K)` and `(K, N)`, respectively, and `C` is unidirectional broadcastable to `(M, N)`. `alpha` and `beta` are scalar multipliers. So, in this example, when the first node in my model `(dense_0)` tries to compute its output to the ReLU, it has `A = (K)` when it needs `A = (M,K)`, where `M=1`.

The output dimension is `[784,10]` when it should be `[1,10]`. I am not sure if this is just because `ONNXmutable.jl` doesn't infer the correct dimensionality for the `(dense_1)` node based on the earlier input dimension error at node `(dense_0)` or because it directly miscalculates the dimensionality.

**Comment by DrChainsaw** [comment]
Yikes, that does not sound good. Unit tests cover interoperability with onnxruntime but perhaps there are blind spots.

How do you specify the input shape? I think it should be one of `onnx(model, (784, :B))` `onnx(model, (784, 1))` or `onnx(model, (784, missing))`.  If `model` is a `CompGraph` also `onnx(model)` should work.

If you used `onnx(model, 784)` and that didn't throw an error then that is ofc also an error which needs to be patched.

I'll try out the model and see what happens later tonight. If you can post an MWE it would save me some time but I think the netron picture is suffient.

**Comment by DrChainsaw** [comment]
I tried creating and saving a model like this:

```julia
julia> using ONNXmutable, NaiveNASflux

julia> m = Chain(Dense(784, 32, relu), Dense(32,10))
Chain(Dense(784, 32, relu), Dense(32, 10))

julia> onnx("mnistmlp.onnx", m, (784, :BatchSize))
```

I didn't try to load it with onnxruntime, but now Netron shows the right sizes at least:

![image](https://user-images.githubusercontent.com/36208552/98037616-24306100-1e1c-11eb-9ff2-546dd7922960.png)

I saw that in #26 the example code saves using `onnx(model_filename, m, (784,))`. This should definitely error out instead of resulting in an incorrect model! I'm a bit blocked by #24 now which is basically waiting for BaseOnnx.jl to be registered. I'll add a check for correct input specification as soon as I have that out of the way.

Does this solve your issue?

**Comment by tfburns** [comment]
By changing the save line in my Julia code in the example from `onnx(model_filename, m, (784,))` to `onnx(model_filename, m, (784,1))` this issue (as viewable from Netron) is completely resolved. What's interesting is that loading the model back into Julia with `CompGraph` it loads fine and is usable just as you would expect. The model seems to load in C++ ONNX Runtime, too.

**Comment by DrChainsaw** [comment]
I think that `onnx(name, model, (784, missing))` should work, so I'll look into that as well.

ONNX seems to have quite a number of redundant fields where the input dimensions are one of them. Some are perhaps used to allow for graph optimizations, but I'm thinking the input dimensions are only to help the (human) model receiver understand what to put in there. ONNXmutable does not consider them when importing which I guess is why it works.

Btw, thanks alot for trying out the package and reporting issues. Keep them coming!
