### ISSUE TITLE
Potential issue with serialized data for conv layers

### ISSUE THREAD

**Issue by jonalm** [DrChainsaw/ONNXmutable.jl#41]
I'm trying to convert a Flux model to TensorFlow, via onnx. On the tensorflow side the serialized data complains about the dimensions of the convolution layer, as described here https://github.com/onnx/onnx-tensorflow/issues/859#issuecomment-767014381

I'm not sure where the error originates, but this might be a ONNXmutable.jl issue.

The model is the exact same as described in #39

**Comment by DrChainsaw** [comment]
Thanks for the report! I'll look into it tonight.

In the meantime, see if you can get a second opinion from some other framework. ONNXmutable is tested against onnxruntime and in the test directory there is a helper function which might be useful. I'm not 100% this will work, but something like this:

```julia
# create model as in #39 

julia> cd("test")

(ONNXmutable) pkg> activate .

julia> include("serialize/onnxruntime.jl")

julia> inpt = randn(Float32, 31,54,1);

julia> onnxout = onnxruntime_infer(model, inpt);

julia> onnxout == model(inpt) #Please return true :)
```

**Comment by DrChainsaw** [comment]
Oh, and after reading the comment in the linked tensorflow issue: Make sure you supply the input dimensions when saving the model. There is a chance that tensorflow checks that they are set and consistent and ONNXmutable can't infer them from a `Chain` (only from a `CompGraph`).

```julia
julia> onnx("model.onnx", model, (31,54,1))
```

**Comment by jonalm** [comment]
Thank you so much. The python package for TensorFlow conversion (onnx_tf) does indeed work when I add the input dimensions!

**Comment by DrChainsaw** [comment]
Great!

I keep this open as I think the serialized model is not compliant with the ONNX spec in case of missing input sizes. ONNX says that the shape info shall be missing, but ONNXmutable adds an empty shape info which should be interpreted as a scalar.

I'll also look into improving the shape inference for Chain. Since NaiveNASflux already knows the shapes of all Flux layers one could at least look at the first layer and see if it is something for which the shape is known.

**Comment by DrChainsaw** [comment]
As per the above, exporting with unkown inputshapes (e.g. by omitting them) should now yeild a valid model. If you have the setup to test it easily with onnx_tf I'd appreciate a confirmation that I got it right this time around. :)

Better automatic shape inference for Chains is tracked in #43 and I'll add it as soon as I find the time to do so.

**Comment by jonalm** [comment]
Sure, I will get to it in a couple of days.

**Comment by DrChainsaw** [comment]
I just merged the improved shape inference for chains so I'm closing this.

To export a `Chain` with unkown shape, use `missing` as shapeinfo: `onnx("model.onnx", model, missing)`

**Comment by jonalm** [comment]
FWIW, I can confirm that onnxruntime can import and run predictions on a model created without specifying shape.
